version: '3'
services:
  db:
    image: postgres:13.4
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /usr/share/zoneinfo/America/Santiago:/etc/localtime
    networks:
     - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres_data:
